# Generated by Django 6.0.2 on 2026-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='name',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='student_name',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
