# Generated by Django 6.0.2 on 2026-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_quizresult_name_quizresult_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='student_name',
            field=models.CharField(default='Participant', max_length=100),
        ),
    ]
