# Generated by Django 6.0.2 on 2026-03-15 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_module_options_rename_body_update_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ModulePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='base.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
